version: 2
jobs:
  build:
    branches:
      only:
        - feature/circleci-v2
    docker:
      - image: circleci/ruby:2.3-stretch-node
    steps:
      - checkout
      - run: pwd
      - run: ls -al
      - run: npm install
      - run: ls -al
      - run: rm -rf sonic-pi
      - run: git clone https://github.com/samaaron/sonic-pi.git
      - run: curl https://hosted.weblate.org/download/sonic-pi/tutorial/ja/ -o sonic-pi/etc/doc/lang/sonic-pi-tutorial-ja.po
      - run: sonic-pi/app/server/ruby/bin/i18n-tool.rb -t
      - run: node_modules/.bin/textlint -f junit -o report.xml sonic-pi/etc/doc/generated/ja/tutorial
