version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-stretch-node
    steps:
      - checkout
      - run: npm install
      - run: rm -rf sonic-pi
      - run: git clone https://github.com/samaaron/sonic-pi.git
      - run: curl https://hosted.weblate.org/download/sonic-pi/tutorial/ja/ -o sonic-pi/etc/doc/lang/sonic-pi-tutorial-ja.po
      - run: sonic-pi/app/server/ruby/bin/i18n-tool.rb -t
      - run:
          name: textlint
          command: |
            mkdir -p ~/junit/
            node_modules/.bin/textlint -f junit -o ~/junit/report.xml sonic-pi/etc/doc/generated/ja/tutorial
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
